name: Bedrock Sync

on:
  push:
    branches:
      - main
      
jobs:
  review-copilot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
            
      - name: Install pipx
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipx
  
      - name: Install Review Copilot
        run: |
          pipx install "git+https://${{ secrets.REVIEW_COPILOT_KEY }}@github.com/scs-sandbox/review-copilot.git"
  
      - name: Run Review Copilot Sync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.REVIEW_COPILOT_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.REVIEW_COPILOT_SECRET_ACCESS_KEY }}
          BEDROCK_KNOWLEDGE_BASE_ID: ${{ secrets.REVIEW_COPILOT_BEDROCK_KNOWLEDGE_BASE_ID }}
          BEDROCK_DATASOURCE_ID: ${{ secrets.REVIEW_COPILOT_BEDROCK_DATASOURCE_ID }}
          
        run: |
          review-copilot sync --local-path $GITHUB_WORKSPACE
