name: Respond to Comments

on:
  issue_comment:
    types: [created]

jobs:
  handle-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Respond to PR Comment
        if: ${{ github.event.issue.pull_request }}
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Authenticate GitHub CLI
          echo $GITHUB_TOKEN | gh auth login --with-token

          # Reply to the comment on the pull request
          gh api repos/${{ github.repository }}/issues/$PR_NUMBER/comments \
            -f body='Thank you for your comment! We will review it shortly.'

      - name: Respond to Issue Comment
        if: ${{ !github.event.issue.pull_request }}
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Authenticate GitHub CLI
          echo $GITHUB_TOKEN | gh auth login --with-token

          # Reply to the comment on the issue
          gh api repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments \
            -f body='Thank you for your feedback!'
