name: Review Co-Pilot

on:
  pull_request:
    types: [reopened, opened, synchronize]

jobs:
  review-copilot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install GitHub API library
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
            
      - name: Install pipx
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipx
  
      - name: Install Review Copilot
        run: |
          pipx install "git+https://github.com/scs-sandbox/review-copilot.git"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        
  
      - name: Run Review Copilot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          review-copilot review
